### PR TITLE
[3.0] Fix indexing of empty rows

### LINKED ISSUE #149: [v3] Returning an empty array still index the entity
Inside a custom `Normalizer` returning an empty array still index the entity

hosted_cloud_search_as_a_service___algolia

### PR DESCRIPTION
**Pull request by tristanbes**
The row is no longer sent to Algolia if it's an empty array
closes #149

### CODE REVIEW

File: src/Engine/AlgoliaEngine.php [hunk 1]
```diff
@@ -93,6 +93,10 @@ private function batchUpdate($searchableEntities)
     {
         $data = [];
         foreach ($searchableEntities as $entity) {
+            if (empty($entity->getSearchableArray())) {
+                break;
```
Comment (julienbourdeau) [inline src/Engine/AlgoliaEngine.php]: Looking at this again, I think this should be `continue`, not `break`. We want to skip the current entity but keep looping. What do you think?

File: src/Engine/AlgoliaEngine.php [hunk 2]
```diff
@@ -118,6 +122,9 @@ private function batchDelete($searchableEntities)
...
```
Comment (julienbourdeau) [inline src/Engine/AlgoliaEngine.php]: Same here

**Comment by tristanbes** [comment]
Great catch @julienbourdeau. Not sure it kept working with my large dataset. Maybe because indexation command doesn't process through batchUpdate ?
